language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 1.0.1
before_script:
 - chmod +x ./build.sh
script:
  - ./build.sh --quiet verify
  
language: node_js
"scripts": {
  "test": "vows --spec"
},
